### ISSUE TITLE
Crash upon logoff

### ISSUE THREAD

**Issue by DorkenVader** [AndFChat/AndFChat#62]
USER_COMMENT=null
ANDROID_VERSION=5.1
APP_VERSION_NAME=0.5.0
BRAND=ZTE
PHONE_MODEL=Z813
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: Fragment already added: FListCharSelectionPopup{3dbe970b #0 select_fragment}
	at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1138)
	at android.app.BackStackRecord.run(BackStackRecord.java:757)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by AndFChat-Pandora** [comment]
Should be fixed in upcoming 0.5.1

Will close on release.
